name: Creating docker imgage
on: 
  push:
    branches: [Dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: build-and-push-image
        run: |
          docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.GH_PAT}}
          docker build . -t ghcr.io/suiding007/growly:latest
          docker push ghcr.io/suiding007/growly:latest
